### ISSUE TITLE
Remove NuGet API key

### ISSUE THREAD

**Issue by jamesfoster** [asgerhallas/ShouldBeLike#4]
Hey, just found this project and I really like how you've used DeepEqual :+1: 

If you have any comments/suggestions to make using DeepEqual easier I'd love to hear them. I tried to make it extensible but I know there are pain points.

But yes, I would avoid committing secrets to git, like your NuGet API key. Otherwise anyone could push a version of ShouldBeLike to NuGet.

**Comment by asgerhallas** [comment]
Thanks a lot for looking out and letting me know! Fortunately the uploaded API key is encrypted, and decrypted only by appveyor. I don't know why appveyor chose this way instead of the more usual variables for secrets, it's actually rather cumbersome when the keys expire 😊

And thank you for DeepEqual!
